### ISSUE TITLE
Add support for FONTX fonts

### ISSUE THREAD

**Issue by gingerbeardman** [kreativekorp/bitsnpicas#17]
## About
FONTX format originates from Japanese DOS/V. It is used in many embedded systems, including some PS2 software and LCD displays.

## Spec
- http://elm-chan.org/docs/dosv/fontx_e.html

## Example fonts
- https://github.com/dokkaebi-project/font-archive
- https://github.com/tuupola/embedded-fonts
- https://github.com/Haruroid/HR_FONTX2
- https://vetusware.com/download/FONTX2%20FONTS%20from%20DOSVs%20JA/?id=13138

## Example FONTX to BDF converters
- https://unifoundry.com/pub/japanese/fontx2bdf-1.1.tar.gz
- http://www.wheel.gr.jp/~dai/software/u-fontx2bdf.html
- http://www.wheel.gr.jp/~dai/software/f2b-readme.html

**Comment by RebeccaRGB** [comment]
This is now supported.

**Comment by gingerbeardman** [comment]
Phenomenal! Great support.

Thank you so much.
