### ISSUE TITLE
BDFs using character set JISX0208.1990 open incorrectly mapped

### ISSUE THREAD

**Issue by torridgristle** [kreativekorp/bitsnpicas#2]
[milkjf-JISX0208-1990.zip](https://github.com/kreativekorp/bitsnpicas/files/1692461/milkjf-JISX0208-1990.zip)

BitsNPicas seems to get all if not most of the characters but they end up pushed back to Letterlike Symbols and from there onward they're dispersed.

If I understand this correctly [this page should detail how JISX0208.1990 translates to Unicode](http://charset.7jp.net/jis0208.html).

After looking through the JAR it looks like [this page](http://www.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/JIS0208.TXT) is what you'd find more useful.

[JIS0208-Edit.TXT](https://github.com/kreativekorp/bitsnpicas/files/1692483/JIS0208-Edit.TXT)

And here's that last file without the SJIS column so it's only JIS0208 and Unicode which seems to better match the other files.

**Comment by RebeccaRGB** [comment]
Can you point me to a BDF file using JIS X 0208 encoding?

**Comment by torridgristle** [comment]
The ZIP up top should have the three I was working with at the time, and so there's a larger selection to work with here's [M+ Bitmap Fonts](http://mplus-fonts.osdn.jp/mplus-bitmap-fonts/download/index.html) which uses JISX0208.1990 for the BDFs in the fonts_j directory of the mplus_bitmap_fonts-2.2.4.tar.gz download. The two zips with 1990 in their name in [this directory](http://kanji.zinbun.kyoto-u.ac.jp/~yasuoka/ftp/fonts/) are JISX0208.1990.
