### ISSUE TITLE
How can I open the glyph list of the subtable?

### ISSUE THREAD

**Issue by diaowinner** [kreativekorp/bitsnpicas#28]
I compiled the latest release and noticed that in some encodings there are a yellow box called "Subtable". How can I open the glyph list of the subtable just like clicking the gray box in the [ICU Converter Explorer](https://icu4c-demos.unicode.org/icu-bin/convexp?conv=windows-936-2000)?

**Comment by RebeccaRGB** [comment]
Expand the tree under the encoding to show the subtables:

![Screenshot from 2022-08-15 20-48-12](https://user-images.githubusercontent.com/1642055/184793997-d96c5223-ca85-452d-a097-5b18f3a6fc00.png)

**Comment by diaowinner** [comment]
Thank you.
