### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pjalsGit** [kreativekorp/bitsnpicas#30]
This project does not have a license, which means:

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.
> - https://choosealicense.com/no-permission/, https://creativecommons.org/licenses/by/3.0/

I would recommend the GPLv3-or-later for this, since you definitely don't want a permissive license like MIT/Expat/X11.

**Comment by gingerbeardman** [comment]
It's MPL https://github.com/kreativekorp/bitsnpicas/blob/master/main/java/BitsNPicas/LICENSE

**Comment by pjalsGit** [comment]
Huh, didn't see that. Maybe it should be made clearer.
