### ISSUE TITLE
Remove downloads/

### ISSUE THREAD

**Issue by ghost** [kreativekorp/bitsnpicas#31]
You shouldn't share pre-compiled binares in the source code. That's what the Releases section is for.

**Comment by gingerbeardman** [comment]
Says who?

**Comment by pjalsGit** [comment]
One of the gitignores made by GitHub: https://gist.github.com/octocat/9257657 and countless projects that don't have precompiled binaries in their source code.

**Comment by gingerbeardman** [comment]
I am sure there is a good reason that the author has them in there.
