### ISSUE TITLE
Change keyboard shortcut for switch between adjacent glyphs

### ISSUE THREAD

**Issue by quiple** [kreativekorp/bitsnpicas#33]
<img width="289" alt="화면 캡처 2022-12-23 112342" src="https://user-images.githubusercontent.com/11014257/209258389-e7a1fe52-2f72-4681-9e60-06797fd2a85a.png">

This feature is great, but these keyboard shortcuts are hard to press with one hand. I tried with using the `right control`, but it didn't work.

`Page Up` & `Page Down` would be nice, how about it?

**Comment by diaowinner** [comment]
In my MacBook the "Next Glyph" is "command + ]", but the PgDn goes to "fn + down". It seems to feel uncomfortable.  
But right command key works for my macOS. The bug is only on Windows (or Linux, I donno).
