### ISSUE TITLE
Copy & Paste Graphics in Glyphs

### ISSUE THREAD

**Issue by diaowinner** [kreativekorp/bitsnpicas#40]
Hi, I would like to add a feature.  I am a CJK font designer and it's a pity that this tool doesn't have any selection copy & paste in the graphics in glyphs.

So what is it?  When I want to design glyph 该, I'll use the 讠 compoment and the 亥 in char 核.  Previously I paste the 核 into the 该 codepoints, and replace the 木 to 讠 manually.  If this function is added, I can easily paste the 讠 components.
Looking forward to your reply.

**Comment by gingerbeardman** [comment]
Use `Edit > Paste Into` menu item

**Comment by diaowinner** [comment]
Thanks
