### ISSUE TITLE
Contents of BitsNPicas.app.zip are old

### ISSUE THREAD

**Issue by gingerbeardman** [kreativekorp/bitsnpicas#44]
- latest release is 2.0.2 dated 26 September 2023
- the files inside `BitsNPicas.app.zip` are v2.0 from 14 September 2023

Workaround
- I downloaded the 2.0.2 `BitsNPicas.jar` and replaced the one inside the .app package myself, which seems to give me a version that fixes https://github.com/kreativekorp/bitsnpicas/issues/43

**Comment by RebeccaRGB** [comment]
Release files have been updated.
