### ISSUE TITLE
KSFL not in the classpath (dfont conversion)

### ISSUE THREAD

**Issue by WillGreen** [kreativekorp/bitsnpicas#46]
I'm trying to convert a BDF font to dfont for use on my Mac (M1 running Sonoma 14.2.1 with openjdk 21.0.1 2023-10-17 LTS).

Bits'N'Picas 2.0.2 launches fine and I can successfully convert the BDF font to TrueType. However, when I attempt to convert to dfont it says: "The selected format requires KSFL, but KSFL is not in the classpath."

I found [KSFL](https://github.com/kreativekorp/ksfl) is another of your repos,  but I can't get it to build using the Makefile. I have attached the log from running make in KSFL: [ksfl-make.log](https://github.com/kreativekorp/bitsnpicas/files/13860212/ksfl-make.log)

Could KSFL be included in the jar? Or could you provide advice on how to compile it?

TIA

**Comment by RebeccaRGB** [comment]
There should be an already-built KSFL.jar in the main/java/BitsNPicas/dep
directory.

If you need to compile a new one, it looks like all the errors are just
from building the JavaDocs, so you can do `make KSFL.jar` instead of just
`make` to skip that step.

**Comment by WillGreen** [comment]
Thanks for the quick reply.

I fixed the problem by putting the `dep` folder in the same folder as BitsNPicas.jar and running:

```shell
java -cp dep -jar BitsNPicas.jar
```

It would be helpful if the need for the dep folder was mentioned in the README.

**Comment by RebeccaRGB** [comment]
The newest release no longer depends on KSFL.
