### ISSUE TITLE
Feature request: Import Amiga fonts

### ISSUE THREAD

**Issue by shred** [kreativekorp/bitsnpicas#47]
At the moment, I use [Fony](http://hukka.ncn.fi/index.php?fony) to convert Amiga fonts to BDF files, and then Bits'N'Picas to convert BDF to TTF. It would be great if I could skip the Fony step, and import Amiga bitmap fonts straight into this tool.

I found [this blog article](https://andrewgraham.dev/blog/amiga-bitmap-fonts-part-1-introduction/) which is explaining the structure of the Amiga font files.

Thank you!

**Comment by RebeccaRGB** [comment]
The newest release supports Amiga fonts.
