### ISSUE TITLE
can't run injectcbdt command

### ISSUE THREAD

**Issue by pancao** [kreativekorp/bitsnpicas#5]
Usage:
  java -jar BitsNPicas.jar edit <files>
  java -jar BitsNPicas.jar convertbitmap <options> <files>
  java -jar BitsNPicas.jar viewbitmap <files>
  java -jar BitsNPicas.jar extractsbix <files>
  java -jar BitsNPicas.jar injectsbix <files>
  java -jar BitsNPicas.jar extractsvg <files>
  java -jar BitsNPicas.jar injectsvg <files>
  java -jar BitsNPicas.jar imagetosvg <options> <files>

**Comment by dcunited001** [comment]
The jar in the `./downloads/` hasn't been built with the most recent version. The CBDT extraction commands are listed in [Main.java](https://github.com/kreativekorp/bitsnpicas/blob/1ba00f498651400bdca1d54e1fd6239c112bf5b4/main/java/BitsNPicas/src/com/kreative/bitsnpicas/main/Main.java).

If you clone the repo, browse to the `./main/java/BitsNPicas` folder, there is a Makefile. From this folder, I was able to simply run `make` and it built the project into a JAR for me.

**Comment by dcunited001** [comment]
Also, kudos to whoever decided to include the Makefile in this java project. Not only do you have a sense of humor, it also saved me from downloading JetBrains.

**Comment by RebeccaRGB** [comment]
The downloads directory has been updated with the newest version which includes injectcbdt.
