### ISSUE TITLE
app does not work on sonoma

### ISSUE THREAD

**Issue by mrbbp** [kreativekorp/bitsnpicas#50]
<img width="204" alt="Capture d’écran 2024-02-08 à 18 15 35" src="https://github.com/kreativekorp/bitsnpicas/assets/1716290/0b0e0961-decb-4f7b-9a50-b8c9a2051c80">

**Comment by mrbbp** [comment]
<img width="308" alt="Capture d’écran 2024-02-08 à 18 16 13" src="https://github.com/kreativekorp/bitsnpicas/assets/1716290/be9a601e-9fe7-461f-85a7-8aae4574628d">

**Comment by mrbbp** [comment]
idem for BitsnPicas

**Comment by gingerbeardman** [comment]
Works for me, are you using the latest release?

<img width="310" alt="Screen shot 2024-02-08 at 18 43 45" src="https://github.com/kreativekorp/bitsnpicas/assets/49612/21800782-f85f-455f-ab24-99c66f30b81f">

**Comment by mrbbp** [comment]
when i uncompressed the zip the file is not good....

<img width="400" alt="Capture d’écran 2024-02-09 à 00 13 42" src="https://github.com/kreativekorp/bitsnpicas/assets/1716290/52c0ab4e-45d4-490e-89cd-42bd179c9aed">

**Comment by mrbbp** [comment]
Ok i found the .app is just a folder.
i remove the extension and macos show it as a folder within 3 app

**Comment by mrbbp** [comment]
the name should be an other .app is confusing

**Comment by gingerbeardman** [comment]
macOS standrd unarchiver will extract the download into a folder called BitsnPicas (no extension at all).

So, the problem might be the unarchiver or process you are using to extract the zip.
