### ISSUE TITLE
Cannot convert .ttf fonts into images

### ISSUE THREAD

**Issue by gpodkowa0302** [kreativekorp/bitsnpicas#6]
Whenever I run the command from the readme "java -jar BitsNPicas.jar extractcbdt <emoji font name>.ttf" the program doesn't recognize the command of 'extractcbdt' and throws a usage response.

**Comment by RebeccaRGB** [comment]
The jar in the downloads directory was out of date. It has been updated with the newest version which includes extractcbdt. Please download the newer version and try again.
